### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by bresson** [johanan/Build-Complex-Express-Sites-with-Redis-and-Socket.io#1]
Hi J, 

The source code of Build Complex Express Sites with Redis and Socket.io is missing chapters 4, 5 and 6.

**Comment by johanan** [comment]
Do you know what was covered in those chapters? I ask because the code and videos I created didn't have the same names. My code was broken into volumes and sections.

**Comment by bresson** [comment]
It looks like the "Volume2" directory is mislabeled. Inside the directory are subfolders titled "Section1", "Section2", Section3." These sections actually contain material from Chapter 4, 5 and 6. I'll close the comment. By the way, great course!

**Comment by johanan** [comment]
It looks like I will need to rename/reorganize the repo to match what is in the course. Thanks and I am glad you are enjoying the course.
